name = "NLL"
grammar = "nll"
path_suffixes = ["nll"]
line_comments = ["# "]

[block_comment]
start = "/*"
end = "*/"

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "\""
end = "\""
close = true
newline = false
not_in = ["string"]

autoclose_before = ",]})"
