//! `nlink-lab docs-gen`.

use std::path::PathBuf;

use crate::Cli;
use crate::ctx::Ctx;
use clap::CommandFactory;

#[derive(clap::Args)]
pub struct Args {
    /// Output directory.
    #[arg(long, default_value = "docs/cli")]
    pub out: PathBuf,

    /// Also write the JSON Schemas of every typed `--json` payload
    /// (generated with `schemars`) into this directory.
    #[arg(long, value_name = "DIR")]
    pub schemas: Option<PathBuf>,
}

pub fn run(_ctx: &Ctx, args: Args) -> nlink_lab::Result<()> {
    let Args { out, schemas } = args;
    if let Some(dir) = schemas {
        std::fs::create_dir_all(&dir)?;
        let mut n = 0;
        for (stem, schema) in crate::output::all_schemas() {
            let text = serde_json::to_string_pretty(&schema)?;
            std::fs::write(dir.join(format!("{stem}.schema.json")), format!("{text}\n"))?;
            n += 1;
        }
        eprintln!("wrote {n} schemas to {}", dir.display());
    }
    let cmd = Cli::command();
    std::fs::create_dir_all(&out)?;
    let mut written = Vec::new();
    for sub in cmd.get_subcommands() {
        if sub.is_hide_set() {
            continue;
        }
        let name = sub.get_name().to_string();
        let mut sub = sub.clone().name(clap::builder::Str::from(
            format!("nlink-lab {name}").leak() as &'static str,
        ));
        let help = sub.render_long_help().to_string();
        // Hand-written prose above the markers is kept; only the
        // block between them is regenerated (CI diffs the result).
        const START: &str =
            "<!-- cli-ref:start (generated by `nlink-lab docs-gen`; do not edit) -->";
        const END: &str = "<!-- cli-ref:end -->";
        let block = format!("{START}\n\n```text\n{}\n```\n\n{END}\n", help.trim_end());
        let path = out.join(format!("{name}.md"));
        let page = match std::fs::read_to_string(&path) {
            Ok(existing) if existing.contains(START) && existing.contains(END) => {
                let a = existing.find(START).unwrap_or(0);
                let b = existing
                    .find(END)
                    .map(|i| i + END.len())
                    .unwrap_or(existing.len());
                let tail = existing[b..].trim_start_matches('\n');
                format!(
                    "{}{}{}",
                    &existing[..a],
                    block,
                    if tail.is_empty() {
                        String::new()
                    } else {
                        format!("\n{tail}")
                    }
                )
            }
            Ok(existing) => format!("{}\n\n## Reference\n\n{block}", existing.trim_end()),
            Err(_) => format!("# `nlink-lab {name}`\n\n## Reference\n\n{block}"),
        };
        std::fs::write(&path, page)?;
        written.push(name);
    }
    eprintln!("wrote {} pages to {}", written.len(), out.display());
    Ok(())
}
