//! Resolve a validator/lint `location` string to a source span.
//!
//! [`nlink_lab::ValidationIssue::location`] and
//! [`nlink_lab::LintFinding::location`] are paths into the **lowered**
//! data model (`links[3].addresses[1]`, `networks.core.subnet`,
//! `nodes.r1.routes.10.0.0.0/24`, `impairments."a:eth0"`), not source
//! positions. Editors need positions, so this module maps the path back
//! onto the token stream — using the [`nlink_lab::Topology`] where the
//! path indexes a lowered collection (`links[i]` is an index into
//! `Topology::links`, not into the source's `link` statements).
//!
//! The result is deliberately coarse: a declaration's name, or the
//! statement that declares it. Anything whose name is not literally in
//! the buffer — a node from `for i in 1..4 { node spine${i} }`, a link
//! generated by `mesh`/`ring`/`star`, a `site`-prefixed or imported name
//! — has no source span at all and resolves to [`Resolved::Unknown`];
//! reversing loop expansion is out of scope. Callers surface `Unknown` by
//! reporting at the top of the file with the path appended to the
//! message, so the information is never silently dropped.

use nlink_lab::Topology;
use nlink_lab::parser::nll::lexer::{Spanned, Token};

use super::symbols;

/// How precisely a location was resolved.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Resolved {
    /// The exact token the path names.
    Exact(std::ops::Range<usize>),
    /// The enclosing statement: the leaf segment could not be pinned.
    Statement(std::ops::Range<usize>),
    /// Nothing in the buffer corresponds to this path.
    Unknown,
}

pub struct Resolver<'a> {
    tokens: &'a [Spanned],
    topology: Option<&'a Topology>,
}

/// One path segment.
enum Seg {
    Name(String),
    Index(usize),
}

/// Split the leading segment off a location path. `rest` keeps its
/// leading `.` or `[` so the caller can keep peeling.
fn take_seg(path: &str) -> Option<(Seg, &str)> {
    let path = path.strip_prefix('.').unwrap_or(path);
    if let Some(inner) = path.strip_prefix('[') {
        let end = inner.find(']')?;
        let idx = inner[..end].parse().ok()?;
        return Some((Seg::Index(idx), &inner[end + 1..]));
    }
    if let Some(inner) = path.strip_prefix('"') {
        let end = inner.find('"')?;
        return Some((Seg::Name(inner[..end].to_string()), &inner[end + 1..]));
    }
    if path.is_empty() {
        return None;
    }
    let end = path.find(['.', '[']).unwrap_or(path.len());
    Some((Seg::Name(path[..end].to_string()), &path[end..]))
}

fn take_name(path: &str) -> Option<(String, &str)> {
    match take_seg(path)? {
        (Seg::Name(n), rest) => Some((n, rest)),
        _ => None,
    }
}

fn take_index(path: &str) -> Option<(usize, &str)> {
    match take_seg(path)? {
        (Seg::Index(i), rest) => Some((i, rest)),
        _ => None,
    }
}

/// Field names in a location path whose source spelling is singular.
fn source_word(field: &str) -> &str {
    match field {
        "routes" => "route",
        "vlans" => "vlan",
        "vrfs" => "vrf",
        "ports" => "port",
        "volumes" => "volume",
        "profiles" => "profile",
        "rules" => "rule",
        "peers" => "peer",
        "impairments" => "impair",
        other => other,
    }
}

impl<'a> Resolver<'a> {
    pub fn new(tokens: &'a [Spanned], topology: Option<&'a Topology>) -> Self {
        Self { tokens, topology }
    }

    /// Best source span for a structural location path.
    pub fn resolve(&self, location: &str) -> Resolved {
        let Some((Seg::Name(head), rest)) = take_seg(location) else {
            return Resolved::Unknown;
        };
        match head.as_str() {
            "lab" => self.keyword_block(|t| matches!(t, Token::Lab), None, rest),
            "nodes" => self.declared(|t| matches!(t, Token::Node), rest),
            "profiles" => self.declared(|t| matches!(t, Token::Profile), rest),
            "networks" => self.declared(|t| matches!(t, Token::Network), rest),
            "pools" => self.declared(|t| matches!(t, Token::Pool), rest),
            "links" => self.link(rest),
            "impairments" => self.endpoint_keyed(|t| matches!(t, Token::Impair), rest),
            "rate_limits" => self.endpoint_keyed(|t| matches!(t, Token::Rate), rest),
            "qdiscs" => self.endpoint_keyed(|t| matches!(t, Token::Ident(w) if w == "qdisc"), rest),
            "assertions" => self.nth_in_block(|t| matches!(t, Token::Validate), rest),
            "scenarios" => self.indexed_decl(|t| matches!(t, Token::Scenario), rest),
            "benchmarks" => self.indexed_decl(|t| matches!(t, Token::Benchmark), rest),
            _ => Resolved::Unknown,
        }
    }

    /// Index of the statement head token matching `kw`, optionally
    /// followed by the name `want`, in statement position.
    fn head(&self, kw: impl Fn(&Token) -> bool, want: Option<&str>) -> Option<usize> {
        (0..self.tokens.len()).find(|&i| {
            kw(&self.tokens[i].token)
                && symbols::is_stmt_start(self.tokens, i)
                && match want {
                    None => true,
                    Some(name) => matches!(
                        self.tokens.get(i + 1).map(|t| &t.token),
                        Some(Token::Ident(n) | Token::String(n)) if n == name
                    ),
                }
        })
    }

    /// `nodes.NAME[.field…]`, `networks.NAME.subnet`, …
    fn declared(&self, kw: impl Fn(&Token) -> bool, rest: &str) -> Resolved {
        let Some((name, rest)) = take_name(rest) else {
            // Bare `nodes` / `networks`: point at the first such statement.
            return match self.head(&kw, None) {
                Some(i) => Resolved::Statement(self.tokens[i].span.clone()),
                None => Resolved::Unknown,
            };
        };
        let Some(head) = self.head(&kw, Some(&name)) else {
            return Resolved::Unknown;
        };
        let name_span = self.tokens[head + 1].span.clone();
        if rest.is_empty() {
            return Resolved::Exact(name_span);
        }
        match self.refine(head, rest) {
            Some(span) => Resolved::Exact(span),
            None => Resolved::Statement(name_span),
        }
    }

    /// `lab`, `lab.mgmt`, `lab.routing`, …
    fn keyword_block(
        &self,
        kw: impl Fn(&Token) -> bool,
        want: Option<&str>,
        rest: &str,
    ) -> Resolved {
        let Some(head) = self.head(&kw, want) else {
            return Resolved::Unknown;
        };
        if rest.is_empty() {
            return Resolved::Exact(self.tokens[head].span.clone());
        }
        match self.refine(head, rest) {
            Some(span) => Resolved::Exact(span),
            None => Resolved::Statement(self.tokens[head].span.clone()),
        }
    }

    /// `links[i]`, `links[i].endpoints[j]`, `links[i].addresses[j]`.
    ///
    /// `i` indexes `Topology::links`, so the endpoints come from the
    /// lowered link and are then looked up as `node : iface` in the
    /// token stream.
    fn link(&self, rest: &str) -> Resolved {
        let Some((idx, rest)) = take_index(rest) else {
            return Resolved::Unknown;
        };
        let Some(link) = self.topology.and_then(|t| t.links.get(idx)) else {
            return Resolved::Unknown;
        };
        let eps: Vec<_> = link
            .endpoints
            .iter()
            .filter_map(|e| nlink_lab::EndpointRef::parse(e))
            .collect();
        if eps.len() != 2 {
            return Resolved::Unknown;
        }
        let Some(head) = self.link_head(&eps) else {
            return Resolved::Unknown;
        };
        // Which half of the statement, and which address?
        let (field, sub) = match take_seg(rest) {
            Some((Seg::Name(f), sub)) => (f, sub),
            _ => return Resolved::Exact(self.link_span(head)),
        };
        let j = take_index(sub).map(|(j, _)| j);
        match (field.as_str(), j) {
            ("endpoints", Some(j)) => {
                // `link a:eth0 -- b:eth0`: endpoint 0 is at head+1, and
                // endpoint 1 follows the `--`.
                let start = if j == 0 {
                    head + 1
                } else {
                    match self.tokens[head..]
                        .iter()
                        .position(|t| matches!(t.token, Token::DashDash))
                    {
                        Some(off) => head + off + 1,
                        None => return Resolved::Statement(self.link_span(head)),
                    }
                };
                match self.endpoint_span(start) {
                    Some(span) => Resolved::Exact(span),
                    None => Resolved::Statement(self.link_span(head)),
                }
            }
            ("addresses", j) => {
                let want = j
                    .and_then(|j| link.addresses.as_ref().and_then(|a| a.get(j)))
                    .cloned();
                match self.address_span(head, want.as_deref(), j.unwrap_or(0)) {
                    Some(span) => Resolved::Exact(span),
                    None => Resolved::Statement(self.link_span(head)),
                }
            }
            _ => match self.refine(head, rest) {
                Some(span) => Resolved::Exact(span),
                None => Resolved::Statement(self.link_span(head)),
            },
        }
    }

    /// The `link` statement whose two endpoints match `eps`, in either order.
    fn link_head(&self, eps: &[nlink_lab::EndpointRef]) -> Option<usize> {
        (0..self.tokens.len())
            .filter(|&i| {
                matches!(self.tokens[i].token, Token::Link)
                    && symbols::is_stmt_start(self.tokens, i)
            })
            .find(|&i| {
                let found = self.statement_endpoints(i);
                found.len() == 2
                    && ((found[0] == (eps[0].node.clone(), eps[0].iface.clone())
                        && found[1] == (eps[1].node.clone(), eps[1].iface.clone()))
                        || (found[0] == (eps[1].node.clone(), eps[1].iface.clone())
                            && found[1] == (eps[0].node.clone(), eps[0].iface.clone())))
            })
    }

    /// `node : iface` pairs in the statement starting at `head`.
    fn statement_endpoints(&self, head: usize) -> Vec<(String, String)> {
        let mut out = Vec::new();
        for i in head..self.tokens.len() {
            if matches!(self.tokens[i].token, Token::LBrace | Token::Newline) {
                break;
            }
            if let Some(ep) = symbols::endpoint_at(self.tokens, i)
                && matches!(self.tokens[i].token, Token::Ident(_))
                && matches!(self.tokens.get(i + 1).map(|t| &t.token), Some(Token::Colon))
            {
                out.push(ep);
            }
        }
        out
    }

    /// Span of `node:iface` starting at token `i`.
    fn endpoint_span(&self, i: usize) -> Option<std::ops::Range<usize>> {
        let node = self.tokens.get(i)?;
        let iface = self.tokens.get(i + 2)?;
        matches!(node.token, Token::Ident(_)).then_some(())?;
        matches!(self.tokens.get(i + 1)?.token, Token::Colon).then_some(())?;
        Some(node.span.start..iface.span.end)
    }

    /// Span of the statement at `head` up to the end of its line or block head.
    fn link_span(&self, head: usize) -> std::ops::Range<usize> {
        let start = self.tokens[head].span.start;
        let mut end = self.tokens[head].span.end;
        for t in &self.tokens[head..] {
            if matches!(t.token, Token::LBrace | Token::Newline) {
                break;
            }
            end = t.span.end;
        }
        start..end
    }

    /// The address token in the statement at `head`: by value when the
    /// lowered value is known, else the `n`-th address-shaped token.
    fn address_span(
        &self,
        head: usize,
        want: Option<&str>,
        n: usize,
    ) -> Option<std::ops::Range<usize>> {
        let range = symbols::block_range(self.tokens, head).unwrap_or(head..self.tokens.len());
        let mut seen = 0;
        let mut fallback = None;
        for t in &self.tokens[range] {
            let text = match &t.token {
                Token::Cidr(s) | Token::Ipv6Cidr(s) | Token::Ipv4Addr(s) | Token::Ipv6Addr(s) => s,
                Token::Interp(s) => s,
                _ => continue,
            };
            if let Some(want) = want
                && text == want
            {
                return Some(t.span.clone());
            }
            if seen == n {
                fallback = Some(t.span.clone());
            }
            seen += 1;
        }
        fallback
    }

    /// `impairments."a:eth0"` and friends: the statement whose endpoint
    /// matches the quoted `node:iface` key.
    fn endpoint_keyed(&self, kw: impl Fn(&Token) -> bool, rest: &str) -> Resolved {
        let Some((key, rest)) = take_name(rest) else {
            return Resolved::Unknown;
        };
        let Some(want) = nlink_lab::EndpointRef::parse(&key) else {
            return Resolved::Unknown;
        };
        let head = (0..self.tokens.len()).find(|&i| {
            kw(&self.tokens[i].token)
                && symbols::is_stmt_start(self.tokens, i)
                && self
                    .statement_endpoints(i)
                    .first()
                    .is_some_and(|(n, f)| *n == want.node && *f == want.iface)
        });
        let Some(head) = head else {
            return Resolved::Unknown;
        };
        let ep = self
            .endpoint_span(head + 1)
            .unwrap_or_else(|| self.tokens[head].span.clone());
        if rest.is_empty() {
            return Resolved::Exact(ep);
        }
        match self.refine(head, rest) {
            Some(span) => Resolved::Exact(span),
            None => Resolved::Statement(ep),
        }
    }

    /// `assertions[i]`: the i-th statement inside the `validate` block.
    fn nth_in_block(&self, kw: impl Fn(&Token) -> bool, rest: &str) -> Resolved {
        let Some(head) = self.head(&kw, None) else {
            return Resolved::Unknown;
        };
        let Some(block) = symbols::block_range(self.tokens, head) else {
            return Resolved::Statement(self.tokens[head].span.clone());
        };
        let Some((idx, _)) = take_index(rest) else {
            return Resolved::Statement(self.tokens[head].span.clone());
        };
        match self.nth_statement(block, idx) {
            Some(span) => Resolved::Exact(span),
            None => Resolved::Statement(self.tokens[head].span.clone()),
        }
    }

    /// `scenarios[i]…` / `benchmarks[i]…`: the i-th such declaration.
    fn indexed_decl(&self, kw: impl Fn(&Token) -> bool, rest: &str) -> Resolved {
        let Some((idx, _)) = take_index(rest) else {
            return Resolved::Unknown;
        };
        let head = (0..self.tokens.len())
            .filter(|&i| kw(&self.tokens[i].token) && symbols::is_stmt_start(self.tokens, i))
            .nth(idx);
        match head {
            Some(i) => Resolved::Statement(
                self.tokens
                    .get(i + 1)
                    .map(|t| t.span.clone())
                    .unwrap_or_else(|| self.tokens[i].span.clone()),
            ),
            None => Resolved::Unknown,
        }
    }

    /// The `n`-th newline-separated statement in a token range.
    fn nth_statement(
        &self,
        range: std::ops::Range<usize>,
        n: usize,
    ) -> Option<std::ops::Range<usize>> {
        let mut seen = 0usize;
        let mut i = range.start;
        while i < range.end {
            if matches!(self.tokens[i].token, Token::Newline) {
                i += 1;
                continue;
            }
            let start = self.tokens[i].span.start;
            let mut end = self.tokens[i].span.end;
            let mut depth = 0i32;
            while i < range.end {
                match self.tokens[i].token {
                    Token::LBrace => depth += 1,
                    Token::RBrace => depth -= 1,
                    Token::Newline if depth == 0 => break,
                    _ => {}
                }
                end = self.tokens[i].span.end;
                i += 1;
            }
            if seen == n {
                return Some(start..end);
            }
            seen += 1;
        }
        None
    }

    /// Find the field a location tail names inside the statement's block.
    ///
    /// Values that appear literally in the source (a route destination, a
    /// VLAN id) are matched by text; otherwise the field's source keyword
    /// is looked up. Returns `None` when neither is present, and the
    /// caller falls back to the statement.
    fn refine(&self, head: usize, rest: &str) -> Option<std::ops::Range<usize>> {
        let block = symbols::block_range(self.tokens, head)?;
        let (field, tail) = take_name(rest)?;
        let word = source_word(&field);
        let field_tok = self.tokens[block.clone()]
            .iter()
            .position(|t| symbols::word(&t.token).as_deref() == Some(word))
            .map(|off| block.start + off);
        // A literal leaf (`routes.10.0.0.0/24`, `vlans.100`) beats the keyword.
        let leaf = tail.strip_prefix('.').unwrap_or(tail);
        if !leaf.is_empty()
            && let Some(t) = self.tokens[block.clone()]
                .iter()
                .find(|t| symbols::word(&t.token).as_deref() == Some(leaf))
        {
            return Some(t.span.clone());
        }
        let field_tok = field_tok?;
        // `rules[i]` / `exec[i]`: the i-th statement of the field's block.
        if let Some((idx, _)) = take_index(tail)
            && let Some(inner) = symbols::block_range(self.tokens, field_tok)
            && let Some(span) = self.nth_statement(inner, idx)
        {
            return Some(span);
        }
        Some(self.tokens[field_tok].span.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nlink_lab::parser::nll::lexer::lex;

    const SRC: &str = concat!(
        "lab \"t\" {\n  routing auto\n}\n",
        "profile router { forward ipv4 }\n",
        "node r1 : router {\n  route default via 10.0.0.2\n  route 10.9.0.0/24 via 10.0.0.2\n}\n",
        "node h1\n",
        "network core { subnet 10.9.0.0/24 members [r1:eth1] }\n",
        "link r1:eth0 -- h1:eth0 { 10.0.0.1/24 -- 10.0.0.2/24 }\n",
        "impair h1:eth0 delay 10ms\n",
        "validate {\n  reach r1 h1\n  reach h1 r1\n}\n",
    );

    fn setup() -> (Vec<Spanned>, Topology) {
        (
            lex(SRC).unwrap(),
            nlink_lab::parser::nll::parse(SRC).unwrap(),
        )
    }

    fn text_of(r: &Resolved) -> &'static str {
        match r {
            Resolved::Exact(s) | Resolved::Statement(s) => {
                let leaked: &'static str = Box::leak(SRC[s.clone()].to_string().into_boxed_str());
                leaked
            }
            Resolved::Unknown => "<unknown>",
        }
    }

    #[test]
    fn resolves_a_node_name_exactly() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("nodes.r1");
        assert!(matches!(r, Resolved::Exact(_)), "{r:?}");
        assert_eq!(text_of(&r), "r1");
    }

    #[test]
    fn resolves_a_network_subnet_to_the_keyword() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("networks.core.subnet");
        assert_eq!(text_of(&r), "subnet");
    }

    #[test]
    fn resolves_a_route_destination_by_value() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("nodes.r1.routes.10.9.0.0/24");
        assert_eq!(text_of(&r), "10.9.0.0/24");
    }

    #[test]
    fn resolves_a_node_field_to_its_keyword() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("nodes.r1.routes");
        assert_eq!(text_of(&r), "route");
    }

    #[test]
    fn resolves_a_link_index_through_the_topology() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("links[0]");
        assert_eq!(text_of(&r), "link r1:eth0 -- h1:eth0");
    }

    #[test]
    fn resolves_a_link_endpoint_index() {
        let (t, topo) = setup();
        let res = Resolver::new(&t, Some(&topo));
        assert_eq!(text_of(&res.resolve("links[0].endpoints[0]")), "r1:eth0");
        assert_eq!(text_of(&res.resolve("links[0].endpoints[1]")), "h1:eth0");
    }

    #[test]
    fn resolves_a_link_address_index_by_value() {
        let (t, topo) = setup();
        let res = Resolver::new(&t, Some(&topo));
        assert_eq!(
            text_of(&res.resolve("links[0].addresses[1]")),
            "10.0.0.2/24"
        );
    }

    #[test]
    fn resolves_a_quoted_endpoint_key() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("impairments.\"h1:eth0\"");
        assert_eq!(text_of(&r), "h1:eth0");
    }

    #[test]
    fn resolves_a_lab_field() {
        let (t, topo) = setup();
        let res = Resolver::new(&t, Some(&topo));
        assert_eq!(text_of(&res.resolve("lab")), "lab");
        assert_eq!(text_of(&res.resolve("lab.routing")), "routing");
    }

    #[test]
    fn resolves_an_assertion_index() {
        let (t, topo) = setup();
        let res = Resolver::new(&t, Some(&topo));
        assert_eq!(text_of(&res.resolve("assertions[1]")), "reach h1 r1");
    }

    #[test]
    fn falls_back_to_the_statement_when_the_field_is_absent() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("nodes.r1.image");
        assert!(matches!(r, Resolved::Statement(_)), "{r:?}");
        assert_eq!(text_of(&r), "r1");
    }

    #[test]
    fn a_loop_generated_node_is_unknown() {
        let src = "lab \"t\"\nfor i in 1..3 {\n  node spine${i}\n}\n";
        let t = lex(src).unwrap();
        let topo = nlink_lab::parser::nll::parse(src).unwrap();
        assert!(topo.nodes.contains_key("spine1"));
        let r = Resolver::new(&t, Some(&topo)).resolve("nodes.spine1");
        assert_eq!(r, Resolved::Unknown);
    }

    #[test]
    fn an_unknown_head_is_unknown() {
        let (t, topo) = setup();
        let res = Resolver::new(&t, Some(&topo));
        assert_eq!(res.resolve("widgets.foo"), Resolved::Unknown);
        assert_eq!(res.resolve(""), Resolved::Unknown);
    }

    #[test]
    fn a_link_index_past_the_end_is_unknown() {
        let (t, topo) = setup();
        let r = Resolver::new(&t, Some(&topo)).resolve("links[99]");
        assert_eq!(r, Resolved::Unknown);
    }

    #[test]
    fn works_without_a_topology_for_named_paths() {
        let (t, _) = setup();
        let res = Resolver::new(&t, None);
        assert_eq!(text_of(&res.resolve("nodes.h1")), "h1");
        // `links[i]` needs the lowered topology and degrades honestly.
        assert_eq!(res.resolve("links[0]"), Resolved::Unknown);
    }
}
